---
- name: setup firewall rules
  hosts: all

  tasks:
    - name: disable SELinux
      selinux:
        state: disabled
      register: selinux_result

    - name: install a list of packages
      yum:
        name:
          - firewalld
        state: present
      register: yum_firewalld_result

    - name: reboot the machine if necessary
      reboot:
      when: selinux_result.reboot_required or yum_firewalld_result.changed

    - name: start service firewalld, if not started
      service:
        name: firewalld
        enabled: yes
        state: started

    - name: disable http for public
      firewalld:
        zone: public
        service: http
        permanent: yes
        state: disabled

    - name: enable http for home
      firewalld:
        zone: home
        source: 192.168.0.2
        service: http
        permanent: yes
        state: enabled
